name = "emp3r0r-cf-relay"
main = "src/worker.js"
workers_dev = false
routes = [ { pattern = "relay.ubx1ujnzri.kdns.fr/*", zone_id = "b5862c93897117dd67d5e38c8f291367" } ]
compatibility_date = "2025-03-01"

[[durable_objects.bindings]]
name = "RELAY_DO"
class_name = "RelayDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelayDO"]

[observability]
enabled = false
